version: "3.8"
services: 
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  rmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  
  blog:
    image: "blog"
    ports:
      - 9003
    depends_on: 
      - mongo
      - rmq
      - redis