version: "3.8"
services: 
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    ports:
      - "9003:9003"
    depends_on: 
      - mongo
    restart: always