version: "3.8"
services: 
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "backend"
    container_name: backend
    ports:
      - 9003
    depends_on: 
      - mongo
      - rabbit_mq 
    restart: always