version: "3.8"
services: 
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo/db:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    ports:
      - "9003:9003"
    depends_on: 
      - mongo
    restart: always
  
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    restart: unless-stopped
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS} 
    ports:
      - 15672:15672
      - 5672-5672
    
  background:
    build:
      context: ./
      dockerfile: Dockerfile.celery
    image: ${CELERY_APP_NAME}
    container_name: ${CELERY_APP_NAME}
    depends_on:
      - mongo
      - rabbitmq
    restart: always


