openapi: "3.0.2"

info:
  title: Blog
  version: 0.0.1

components:
  schemas:
    PostPageRequest:
      type: object
      properties:
        page:
          type: integer
        page_size:
          type: integer
    UpdatePost:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        author_id:
          type: string

    CreatePost:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        author_id:
          type: string

    Error:
      type: object
      properties:
        msg:
          type: string

    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        author_id:
          type: string
        comment_ids:
          type: array
          items:
            type: string
