openapi: "3.0.2"

info:
  title: Blog
  version: 0.0.1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RefreshRequest:
      type: object
      properties:
        refresh:
          type: string

    TokenPair:
      type: object
      properties:
        access:
          type: string
        refresh:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    GetUser:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string

    CreateUser:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        first_name:
          type: string
        last_name:
          type: string

    PostPageRequest:
      type: object
      properties:
        page:
          type: integer
        page_size:
          type: integer

    CreatePost:
      type: object
      properties:
        title:
          type: string
        content:
          type: string

    UpdatePost:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    GetPostPageResponse:
      type: object
      properties:
        "items":
          type: "array"
          items:
            $ref: "#components/schemas/Post"
        page:
          type: integer
        page_size:
          type: integer
        page_count:
          type: integer
    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        author_id:
          type: string
        comment_ids:
          type: array
          items:
            type: string

    Error:
      type: object
      properties:
        msg:
          type: string
